"""empty message

Revision ID: a0dbac6b0e06
Revises: 
Create Date: 2020-06-25 23:44:08.054146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0dbac6b0e06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attractions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('info', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('picture_link', sa.String(length=500), nullable=True),
    sa.Column('c_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('info', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('picture_link', sa.String(length=500), nullable=True),
    sa.Column('c_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('c_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('attrcomm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('attr_id', sa.Integer(), nullable=True),
    sa.Column('user_phone', sa.Integer(), nullable=True),
    sa.Column('info', sa.String(length=500), nullable=True),
    sa.Column('attrname', sa.String(length=128), nullable=True),
    sa.Column('c_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attr_id'], ['attractions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attrorder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('attr_id', sa.Integer(), nullable=True),
    sa.Column('user_phone', sa.Integer(), nullable=True),
    sa.Column('info', sa.String(length=128), nullable=True),
    sa.Column('order_status', sa.Boolean(), nullable=True),
    sa.Column('c_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attr_id'], ['attractions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotelcomm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('user_phone', sa.Integer(), nullable=True),
    sa.Column('info', sa.String(length=500), nullable=True),
    sa.Column('hotelname', sa.String(length=128), nullable=True),
    sa.Column('c_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotelorder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('user_phone', sa.Integer(), nullable=True),
    sa.Column('info', sa.String(length=128), nullable=True),
    sa.Column('order_status', sa.Boolean(), nullable=True),
    sa.Column('c_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotelorder')
    op.drop_table('hotelcomm')
    op.drop_table('attrorder')
    op.drop_table('attrcomm')
    op.drop_table('user')
    op.drop_table('hotel')
    op.drop_table('attractions')
    # ### end Alembic commands ###
